ArneBinder/pytorch-ie

src/pytorch_ie/core/document.py, tests/test_document.py
With this PR, the predictions are serialized along with the annotations.
Note: `tests_no_local_datasets` is passing and also half of `tests_only_local_datasets` (I canceled in between).
=> serialize predictions

README.md
[preview](https://github.com/ChristophAlt/pytorch-ie/tree/docs_how_to_create_a_dataset#-datasets) (see expandable item "How to create your own Pytorch-IE dataset")
=> readme: explain how to create your own PIE dataset loading script

poetry.lock, pyproject.toml, tests/data/test_dataset.py
Oddly enough, the dataset loading script you get is dependent on the version of the datasets library.
=> Fix: CoNLL03 loads outdated version

.github/workflows/tests.yml
run tests only on push to main and pull_request to main and releases (fixes #151)
=> don't run tests twice

src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_simple_text_classification.py
This adds a very simple, but well documented taskmodule intended as introductory example.
Note: This ~is re-implemented and~ tested in the PIE template, see [here](https://github.com/ChristophAlt/pytorch-ie-hydra-template/pull/36).
=> simple text classification taskmodule

src/pytorch_ie/core/taskmodule.py
This PR modifies `encode_targets()` in the following way:
Given a list of task encodings, get and assign the respective target encodings and **return all task encodings that got a target**. Only the resulting task encodings are returned from `encode()`.
In that means, this will filter out all encodings without a target. This can be useful when different sets of encodings are required for training and inference. It mitigates the need to implement special logic that depends on target information in encode_input(). Encodings that are not suitable for training, i.e. where no target information is available, can be filtered out easily by letting encode_target() return None.
Note: This is a breaking change because it modifies the expected logic of `encode_targets()`. However, usually only …
=> filter out task encodings in encode_targets() that got no target

src/pytorch_ie/models/transformer_text_classification.py, src/pytorch_ie/models/transformer_token_classification.py
This fixes a bug that was introduced by #217.
=> fix redundant config creation

README.md, src/pytorch_ie/annotations.py
[Rendered](https://github.com/ChristophAlt/pytorch-ie/tree/docs_pie_concepts#-concepts--architecture)
=> docs for pie Concepts & Architecture

src/pytorch_ie/data/builder.py
This incorporates recent changes of Huggingface datasets, especially we 
* overwrite `_as_dataset()` instead of `_post_process()` because this is more in par with how the iterable dataset is handled via `_as_streaming_dataset_single()` and allows to further use (overwrite)  `_post_process()`, and
* use the `fn_kwargs` instead of a partial function (which causes errors in some cases).
=> streamline dataset builder

src/pytorch_ie/taskmodules/transformer_re_text_classification.py
This caused mypy errors in downstream projects (when reusing the taskmodule code as it is in a new one).
=> fix typing in RE taskmodule

src/pytorch_ie/auto.py, tests/pipeline/test_ner_span_classification.py, tests/pipeline/test_re_text_classification.py
This PR adds:
* call `taskmodule._post_prepare()` in `AutoTaskmodule._from_pretrained()`
* auto test cases `test_ner_span_classification` and `test_re_text_classification`
This was missed in #248. It fixes #259.
=> fix AutoTaskmodule

README.md
[[rendered](https://github.com/ChristophAlt/pytorch-ie/blob/project_developement_readme/README.md#-project-development)]
=> add project development section to readme

src/pytorch_ie/models/transformer_span_classification.py, src/pytorch_ie/models/transformer_text_classification.py, tests/models/test_transformer_span_classification.py
=> remove t_total from model implementations

src/pytorch_ie/models/transformer_span_classification.py, src/pytorch_ie/models/transformer_text_classification.py
this fixes a deprecation warning
=> use AdamW from torch.optim instead of the Huggingface transformers version

pyproject.toml
integrating #280 did not trigger any release workflow, so we try again
=> release 0.15.1

src/pytorch_ie/data/builder.py
This PR introduces `GeneratorBasedBuilder.BASE_DATASET_PATHS: Dict[str: str] = {}` to allow to define the Huggingface base dataset path for each PIE dataset config individually.
=> individual Huggingface base dataset per config

tests/taskmodules/test_transformer_token_classification.py
This code was originally written by @akashkumar25.
=> add tests for TransformerTokenClassificationTaskModule

src/pytorch_ie/annotations.py, tests/core/test_document.py, tests/test_document.py
This fixes #304. Requires #305.
=> set compare=False for the score of built-in annotations

poetry.lock, pyproject.toml
... again to >=4.18 and improve dep order
=> set minimum transformers version 

README.md
see https://github.com/ArneBinder/pie-datasets/pull/45 and https://github.com/ArneBinder/pie-datasets/pull/46
[[rendered](https://github.com/ChristophAlt/pytorch-ie/tree/remove_datasets_documentation)]
=> remove datasets related documentation

src/pytorch_ie/core/__init__.py, src/pytorch_ie/core/module_mixins.py
=> add dataset mixins

src/pytorch_ie/core/document.py
=> fix type inference

src/pytorch_ie/core/document.py, tests/test_document.py
This PR adjusts `Document.add_all_annotations_from_other()` to return the annotations from the source document for which a new annotation was added to the target document. This can be useful to check if all original annotations were added (possibly to multiple target documents).
=> `Document.add_all_annotations_from_other()` returns added original annotations

src/pytorch_ie/core/hf_hub_mixin.py
... and also add `PieBaseHFHubMixin.has_config`
=> add `config` property to `PieBaseHFHubMixin`

src/pytorch_ie/metrics/f1.py
This allows to add special mapping logic before the annotations get compared for computing tp / fn / fp counts. 
E.g. using the following method as `annotation_processor` when evaluating binary relations makes the comparison indifferent towards the argument labels:
```python
from typing import Tuple
from pytorch_ie.annotations import BinaryRelation, Span
from pytorch_ie.core import Annotation
def to_binary_relation_without_argument_labels(ann: Annotation) -> Tuple[int, int, int, int, str]:
if not isinstance(ann, BinaryRelation):
raise ValueError("Annotation must be a BinaryRelation")
if not isinstance(ann.head, Span) or not isinstance(ann.tail, Span):
raise ValueError("BinaryRelation must have two Span arguments")
return ann.head.start, ann.head.end, ann.tail.start, ann.tail.end, …
```
=> add `annotation_processor` to `F1Metric`

src/pytorch_ie/core/document.py, tests/test_document.py
=> add `resolve()` to `BaseAnnotationList`

tests/test_auto.py
i.e.,  test_auto_model_full_cycle and test_auto_model_full_cycle_with_name
=> add more auto tests

src/pytorch_ie/datamodule.py
taken from https://github.com/ArneBinder/pytorch-ie-hydra-template-1
=> add `PieDataModule`

examples/predict/ner_span_classification.py, examples/predict/re_generative.py, examples/predict/re_text_classification.py, src/pytorch_ie/__init__.py, src/pytorch_ie/annotations.py, src/pytorch_ie/datamodule.py, src/pytorch_ie/documents.py, src/pytorch_ie/metrics/confusion_matrix.py, src/pytorch_ie/metrics/f1.py, src/pytorch_ie/metrics/statistics.py, src/pytorch_ie/models/transformer_seq2seq.py, src/pytorch_ie/models/transformer_span_classification.py, src/pytorch_ie/models/transformer_text_classification.py, src/pytorch_ie/models/transformer_token_classification.py, src/pytorch_ie/pipeline.py, src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py, src/pytorch_ie/utils/document.py, tests/conftest.py, tests/metrics/test_confusion_matrix.py, tests/metrics/test_f1.py, tests/pipeline/test_ner_span_classification.py, tests/pipeline/test_re_generative.py, tests/pipeline/test_re_text_classification.py, tests/test_auto.py, tests/test_pipeline.py
some cleanup after #456 (was outsourced to keep the former a bit smaller)
=> import from `pie_core` directly

poetry.lock, pyproject.toml
this fixes a regression introduced in #480 
related: #485
=> fix `requires-python` in `pyproject.toml`

src/pytorch_ie/datamodule.py
This PR allows it to easily overwrite that functionality in downstream projects.
some context/motivation: https://github.com/ArneBinder/pie-datasets/pull/200.
=> outsource `encode_documents()` from `PieDataModule.setup()`
