src/pytorch_ie/core/document.py
Usually, multiple annotations are added at once, so this introduces a shortcut for that.
=> implement BaseAnnotationList.extend

src/pytorch_ie/pipeline.py, tests/pipeline/test_ner_span_classification.py
This adds a boolean parameter `fast_dev_run` to the pipeline that allows for similar functionality as the one for training with pytorch-lightning: If enabled, only the first model inputs, i.e the first entry produced by `taskmodule.encode`, will be processed. This is especially useful for cli tests in downstream projects to check if a pipeline runs through without the need to prepare a special dummy dataset.
Note: I successfully ran `tests_no_local_datasets-3.9` locally.
=> fast_dev_run parameter for pipeline 

tests/data/test_dataset.py
The root issues was fixed (see https://huggingface.co/datasets/conll2003/commit/331adb7e97519e443e4c23e33c4805c9fd5a9381), so we can correct the expected numbers.
Note: `nox -p3.9 --session=tests_no_local_datasets` passed.
=> adjust test with conll2003

src/pytorch_ie/core/document.py, tests/test_document.py
Iterating a document failed so far. With this PR, `Document.__iter__` will return just the names of the annotation fields (following the convention for `Mapping`s).
Note: `nox -p3.9 --session=tests_no_local_datasets` passes except one test with external cause (this is fixed in #198).
=> fix iter document

src/pytorch_ie/core/document.py, src/pytorch_ie/documents.py, tests/test_document.py
This simplifies the annotation graph calculation and usage. Instead of saving `target -> source(s)` entries, we now save `source -> target(s)` (i.e. just the dependencies). This is possible by using `_enumerate_dependencies` (instead of `_depth_first_search`) which traverses the graph from sources to targets. A test for `_enumerate_dependencies` is included. Furthermore, this does not require a predefined `_root_annotation` field because we automatically add a node `_artificial_root` to the annotation graph that has all annotation fields that are not targeted as value.
This will also work with multiple base data elements, e.g. a text and an image, out of the box. It is also in preparation for having multiple targets per annotation field (see #210).
Note: This PR is an alternative to #207 …
=> Remove _root_annotation

src/pytorch_ie/core/document.py, src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/data/__init__.py, src/pytorch_ie/data/builder.py, src/pytorch_ie/data/dataset.py, tests/conftest.py, tests/data/test_dataset.py, tests/data/test_dataset_casting.py
This implements `IterableDataset` and allows to pass `streaming=True` to `load_dataset` to get one from any PIE dataset loading script. This is first step towards fully handling streamed datasets, see #144 for the related issue regarding the taskmodule.
Example usage (just works):
```python
import re
from dataclasses import dataclass
import datasets
from pytorch_ie.annotations import LabeledSpan, Span
from pytorch_ie.core import AnnotationList, annotation_field
from pytorch_ie.documents import TextDocument
@dataclass
class DocumentWithEntsAndSents(TextDocument):
ents: AnnotationList[LabeledSpan] = annotation_field(target="text")
sents: AnnotationList[Span] = annotation_field(target="text")
def add_sents_simple(doc: DocumentWithEntsAndSents):
start = 0
for match in re.finditer(r"\.", …
```
=> Iterable dataset

src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/model.py, src/pytorch_ie/models/transformer_seq2seq.py, src/pytorch_ie/models/transformer_span_classification.py, src/pytorch_ie/models/transformer_text_classification.py, src/pytorch_ie/models/transformer_token_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py, tests/models/test_transformer_span_classification.py, tests/pipeline/test_ner_span_classification.py, tests/pipeline/test_re_text_classification.py, tests/taskmodules/test_transformer_re_text_classification.py, tests/taskmodules/test_transformer_span_classification.py
This adds the property `is_from_pretrained` to all classes that inherit from `PyTorchIEBaseModelHubMixin`, especially to taskmodules and models. It allows, for instance, to load a model only from the huggingface hub, if it is really necessary. Previously, the model might be loaded twice from the hub: first when calling e.g. `AutoModel.from_pretrained` and then again in the init of the respective model which calls sth like `transformers.AutoModel.from_pretained`. Now we mitigate that with sth like:
```python
config = transformers.AutoConfig.from_pretrained(model_name_or_path)
if self.is_from_pretrained:
self.model = transformers.AutoModel.from_config(config=config)
else:
self.model = transformers.AutoModel.from_pretrained(model_name_or_path, config=config)
```
See also #114.
Note: To make …
=> is_from_pretrained property

src/pytorch_ie/annotations.py, src/pytorch_ie/core/document.py, tests/test_annotations.py, tests/test_document.py
Example:
```python
@dataclasses.dataclass
class TestDocument(TextDocument):
tokens: AnnotationList[Span] = annotation_field(target="text")
sentences: AnnotationList[Span] = annotation_field(target="text")
doc = TestDocument(text="test1")
token = Span(start=0, end=len(doc.text))
sentence = Span(start=0, end=len(doc.text))
doc.tokens.append(token)
doc.sentences.append(sentence)
doc_dict = doc.asdict()
doc_reconstructed = TestDocument.fromdict(doc_dict)
print(doc_reconstructed.sentences)
print(doc_reconstructed.tokens)
assert doc == doc_reconstructed
```
Before this PR, this failed, because the annotation names were not taken into account when collecting the annotations for reconstruction. See the outcome of `doc_reconstructed.sentences` and `doc_reconstructed.tokens` in the example code …
=> same annotations in different annotation lists

src/pytorch_ie/core/document.py, src/pytorch_ie/data/dataset.py, tests/data/test_dataset.py
This PR adds an optional parameter `document_return_type` to `(Iterable)Dataset`. This is useful if the mapped function returns documents of a different type. Furthermore, `document_return_type` will be inferred from the function return type annotation if possible and no `document_return_type` is explicitly provided.
=> result_document_type for (Iterable)Dataset.map()

src/pytorch_ie/annotations.py, tests/test_annotations.py
`(Multi)LabeledMultiSpan` was broken. When reconstructed from dataset entries, tuples like the slices are returned as lists. This should be fixed in the `__post_init__` method. However, for `(Multi)LabeledMultiSpan`, this was not correctly implemented.  
In addition, this PR:
* fixes various typing errors for annotations
* fixes the tests for annotations
* renames internal methods `_validate_single_label` to `_post_init_single_label` and `_validate_multi_label` to `_post_init_multi_label` for consistency
=> Fix (Multi)LabeledMultiSpan

README.md, examples/predict/ner_span_classification.py, examples/predict/re_generative.py, examples/predict/re_text_classification.py, src/pytorch_ie/pipeline.py, tests/pipeline/test_ner_span_classification.py, tests/pipeline/test_re_generative.py, tests/pipeline/test_re_text_classification.py, tests/test_auto.py, tests/test_pipeline.py
This removes the parameter `predict_field` from the pipeline since it is used only for clearing predictions beforehand which is not necessary in most of the use cases and should be done explicitly, if needed. Furthermore, its meaning is not clear for models that predict multiple fields at once, e.g. joint NER+RE models. It is also confusing for the user because its existence implies that it has any effect on the inner workings of the taskmodule / model.
Note: This PR adds instead the parameter `document_batch_size` to the pipeline which was missed in #218.
=> remove parameter predict_field from pipeline

src/pytorch_ie/annotations.py, src/pytorch_ie/core/document.py, tests/test_annotations.py, tests/test_document.py
This clarifies that the annotation id property is internal and allows the user to define its own "id" field.
=> prefix annotation id with an underscore

src/pytorch_ie/pipeline.py
Before this change, the output of the model was unexpectedly changed to a dict if `model.predict()` returns an instance of `ModelOutput`. This caused issues when implementing `Taskmodule.unbatch_output()`.
=> fix Pipeline._ensure_tensor_on_device() for ModelOutput

src/pytorch_ie/core/hf_hub_mixin.py
When a fine-tuned model was loaded again for fine-tuning or evaluation, it clashed because the parameter `is_from_pretrained` was passed twice (loaded from the config and set as a parameter). With this PR, `is_from_pretrained` is not passed separately, but the config entry is just overwritten with `config["is_from_pretrained"] = True`.
=> fix is_from_pretrained

src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/data/datamodules/datamodule.py
This fixes #241 by adding a boolean parameter `show_progress` to `taskmodule.encode()` and `show_progress_for_encode` to the `Datamodule`. Both are `False` per default.
=> show_progress for taskmodule.encode()

src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/taskmodules/simple_transformer_text_classification.py
This is an alternative to #194, but much less invasive.
* implement:
*  `PREPARED_ATTRIBUTES`: class attribute that defines what attributes need preparation
* `is_prepared`: Returns True, iff all attributes listed in PREPARED_ATTRIBUTES are set. Note: Attributes set to None are not considered to be prepared!
* `prepared_attributes`: Return all prepared attributes as dict.
* `_prepare()`: This method should be overwritten in the respective taskmodule instead of `prepare()`. It needs to set all attributes listed in `PREPARED_ATTRIBUTES`.
* `_post_prepare()`: This method can be overwritten in the respective taskmodule. It should contain any code to do further one-time setup, but that requires the prepared attributes. This is separated from `_prepare()` to allow to execute that code on a …
=> backwards compatible prepare() logic improvements

src/pytorch_ie/taskmodules/transformer_re_text_classification.py, tests/taskmodules/test_transformer_re_text_classification.py
* use method `_post_prepare()` that handles one-time initialization based on outcome of `_prepare()`, see #248 for further details.
* create `argument_markers_to_id` just once in `_post_prepare()` instead of in `encode()` which is called for each document
This significantly speeds up `encode()`. E.g. for KBP37 dataset:
```
[2023-02-13 14:03:14,547][__main__][INFO] - Starting training!                                                                                
encode inputs: 100%|██████████| 15807/15807 [00:02<00:00, 7299.08it/s]                                                                        
encode targets: 100%|██████████| 15807/15807 [00:00<00:00, 227466.26it/s]       
encode inputs: 100%|██████████| 1714/1714 [00:00<00:00, …
```
=> improve RE taskmodule speed

src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py
See #254. This also moves the docstrings to the beginning of the files.
=> use TypeAlias in all taskmodules

src/pytorch_ie/auto.py, src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/model.py, src/pytorch_ie/core/registrable.py, src/pytorch_ie/core/taskmodule.py, tests/test_auto.py
Mainly, this does:
* do not let `PyTorchIETaskmoduleModelHubMixin` inherit from `HyperparametersMixin`, this is handled one level above, i.e. in `PyTorchIEModel`, to separate concerns
* overwrite `_from_pretrained()` in `TaskModule` to call `_post_prepare()` where that is defined (previously, this was done in `PyTorchIETaskmoduleModelHubMixin._from_pretrained()` where `_post_prepare()` may not be available)
In addition, some quality of life changes:
* add class attribute `config_type_key` to `PyTorchIEBaseModelHubMixin`
* add constants `MODEL_CONFIG_NAME`, `TASKMODULE_CONFIG_NAME`, `MODEL_CONFIG_TYPE_KEY`, and `TASKMODULE_CONFIG_TYPE_KEY`
* add helper class `Registrable.name_for_object_class(cls: Type[T], obj: T) -> str` to retrieve the name given an object
=> simplify hf_hub_mixin

README.md, src/pytorch_ie/annotations.py, src/pytorch_ie/core/document.py, tests/core/test_document.py, tests/test_annotations.py
This PR introduces `_get_reference_fields_and_container_types()` that allows to collect all fields that are `Annotation` subclasses, i.e. that are meant to reference another annotation, e.g. `head` and `tail` references in the `BinaryRelation`. These references need special treatment during (de-)serialization because we store only their ids instead of the full objects to not create them multiple times when deserializing them. By using `_get_reference_fields_and_container_types()` we can now handle the most common cases automatically: 
1. annotations containing fields that reference any other annotation (example below: `head` or `tail`), 
2. tuples of 1. (example below: `evidence`), and 
3. optional versions of 1. (example below: `trigger`). 
This means, there is **no need to overwrite** …
=> Improvements for annotations with references

src/pytorch_ie/data/builder.py, tests/data/test_builder.py, tests/fixtures/builder/datasets/wrong_builder_class_config/wrong_builder_class_config.py
This PR implements a PIE version of the `ArrowBasedBuilder` in analogy to the `GeneratorBasedBuilder`. The `ArrowBasedBuilder` is required for any PIE dataset builder that has an `ArrowBasedBuilder` as base_builder such as generic tabular data builders from Huggingface (pandas, parquet, json, sql, text, csv).
To do so, this PR introduces an abstract class `PieDatasetBuilder`. This class is a cleaned version of the previous PIE `GeneratorBasedBuilder`: It primarily overwrites `as_dataset()` and `as_streaming_dataset()`, which are the two entry points to get actual datasets from a Huggingface `DatasetBuilder`, by wrapping the Huggingface datasets into PIE datasets.  
Finally, the PIE variants `GeneratorBasedBuilder` and `ArrowBasedBuilder` derive from that new class and just implement the …
=> implement ArrowBasedBuilder

poetry.lock
This addresses Dependabot alerts 11, 12, and 13.
=> update aiohttp and markdown-it-py

src/pytorch_ie/models/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, tests/models/test_transformer_seq2seq.py, tests/taskmodules/test_transformer_seq2seq.py
This was broken because pytorch-lightning tries to move the output of `TransformerSeq2SeqTaskModule.collate` to a device via `pytorch_lightning.core.datamodule.LightningDataModule.transfer_batch_to_device` that internally uses [`pytorch_lightning.utilities.apply_func.apply_to_collection`](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.utilities.apply_func.html#pytorch_lightning.utilities.apply_func.apply_to_collection). This method fails if any part of the input (arbitrary nested) is a frozen `dataclass` which is the case for our `Annotation`s. To fix this, we simply remove the documents (and also metadata) from the batch since it is not used at all.
Note that this PR also adds tests for the seq2seq taskmodule and the seq2seq model. `nox -p3.9 …
=> fix training seq2seq

src/pytorch_ie/data/builder.py
With this PR, the base_builder config_id gets appended to the hash. Otherwise, the base_builder config arguments are not respected in the cache fingerprint. That could happened when using `base_dataset_kwargs`, `BASE_CONFIG_KWARGS_DICT`, or `BASE_BUILDER_KWARGS_DICT`.
=> fix dataset caching

src/pytorch_ie/core/document.py, src/pytorch_ie/data/dataset.py
This PR
- removes the check for metadata equality of the old fields with respect to their new counterparts when casting a dataset. This caused problems because the target names are saved in metadata, so casting a dataset with also renaming fields would result in different metadata content which is totally fine, but raised an error so far.
- adds a boolean parameter `keep_remaining` (default: `True`) to `Document.as_type()` to disable copying over all fields that are not mentioned in `field_mapping`. That caused problems if the old type contains fields that are not useful for the new type.
=> minor data model improvements

pyproject.toml
It looks like it is is not anymore possible to just use the master branch (caused errors in downstream projects).
=> specify version of poetry-core (build-system)

src/pytorch_ie/taskmodules/transformer_token_classification.py, src/pytorch_ie/utils/span.py
Skip the document with a warning instead of raising an error if there are overlapping spans. This also removes two other pytorch warnings.
=> token classification taskmodule: skip docs with overlapping spans

examples/predict/re_text_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, tests/fixtures/datasets/json/train.json, tests/pipeline/test_re_text_classification.py, tests/taskmodules/test_transformer_re_text_classification.py
Important: This is not backwards compatible because 
- the `argument_markers` are constructed in a different (but reproducible) order! That means, models trained with a previous version do not work with this one because the token ids of the argument markers depend on the insertion order when adding them to the tokenizer vocab.
- this requires to explicitly set `create_relation_candidates=True` if no relations are available, e.g. when used for inference on documents that are created from scratch
=> rework TransformerRETextClassificationTaskModule

src/pytorch_ie/data/builder.py
This PR implements `PieDatasetBuilder.DOCUMENT_TYPES`.
=> individual document type per config name

src/pytorch_ie/data/builder.py
If a HF dataset loading script references relative data urls (see [docred](https://huggingface.co/datasets/docred) for an example), using this as base dataset within a PIE dataset loading script was broken. This PR fixes this issue by setting the  `base_path` of the PIE script to the `base_path` of the HF script.
=> fix relative paths in base dataset builder

src/pytorch_ie/core/document.py, tests/core/test_document.py
Changes within this PR:
- set index = -1 as default value for `BasAnnotationList.pop()` (was `None` before which caused an Exception)
- add `Annotation.is_attached` property that returns True iff `_targets` is set
- add `Annotation.copy(**overrides)`: Create a detached copy of the annotation with the same values as the original (allows overrides).
=> add Annotation.copy()

src/pytorch_ie/core/document.py
It is sometimes the case that we want to do sth. with the cleared (detached) annotations, e.g. when we want to move them to another annotation layer (AnnotationList), from predictions to main annotations or to another document.
=> BaseAnnotationList.clear() returns the contained annotations

src/pytorch_ie/core/document.py, tests/test_document.py
This PR add the properties the following properties to `BaseAnnotationList`: 
- `tagets`: return all targets of the annotation layer as dictionary
- `target`: Target accessor for the annotation layer if it has only one target.
- `target_layers`: return all target layers of the annotation layer as dictionary.
- `target_layer`: Target layer accessor for the annotation layer if it has only one target layer.
Note: We add `target` and `target_layer` because most of the layers have just a single target.
=> implement target getters for BaseAnnotationList

src/pytorch_ie/core/document.py, tests/test_document.py
This PR implements `Document.add_all_annotations_from_other` which allows to add all annotations from another document. 
Furthermore, it has an optional parameter `override_annotation_mapping` which should be a mapping from annotation field names to mappings from annotation IDs to annotations. The effects are two-fold. First, adding any annotation field name as key has the effect that the field is expected to be already handled and no annotations will be added from the other document. Second, if an entry `old_annotation._id` -> `new_annotation` is present in the mapping for a certain field, the `new_annotation` will be used anywhere where the `old_annotation` would have been referenced. This propagates along the annotation graph and can be useful if some annotations are modified, but all …
=> implement `Document.add_all_annotations_from_other`

src/pytorch_ie/core/document.py, tests/test_document.py
This PR
- implements the property `Annotation.non_comparison_fields_and_values`,
- modifies the property `Annotation._id` to include this, and
- adds tests.
By including the non-comparison fields into the id property this avoids de-duplication issues when two annotations differ only in such a field (e.g. a prediction `score`). If they would not be included, one of the annotations would be removed.
This means that it can happen that `hash(annotation1) == hash(annotation1)`, but `annotation1._id != annotation2`. However, this follows the semantics of `dataclasses` with non-comparison fields and the `id()` method, e.g. this holds:
```python
@dataclasses.dataclass(frozen=True)
class A:
x: int = dataclasses.field(compare=False)
a = A(x=0)
b = A(x=1)
assert a == b
assert hash(a) == hash(b) …
```
=> include non-comparison annotion fields in the _id calculation

src/pytorch_ie/core/__init__.py, src/pytorch_ie/core/metric.py, src/pytorch_ie/metrics/__init__.py, src/pytorch_ie/metrics/f1.py, tests/core/test_metric.py, tests/test_metrics.py
This PR implements the `DocumentMetric` interface with the following abstract methods:
- `reset(self)`: Any reset logic that needs to be performed before the metric is called (again).
- `_update(self, document: Document)`: This method is called to update the metric with the new document.
- `_compute(self)`: This method should calculate and return the actual metric value(s).
An instance of such a class can be called with a single document, an iterable of documents, or a dict with values of the latter. In each case, the metric is updated with the documents and the computed metric value is returned. If the input was a dict, the values are calculated per dict value and a dict is returned again (i.e. it can be easily applied to a `DatasetDict`).
The PR also implements the `F1Metric` as a …
=> implement DocumentMetric and F1Metric

src/pytorch_ie/core/document.py, tests/test_document.py
There might be edge cases where the previous algorithm did not work (e.g. a dependency graph with `a -> [b,c], c -> [b]`; here the old order would be `[a, b, c]`, but `b` requires `c` to be processed first). So, with this PR, `_enumerate_dependencies()` is used instead which is well tested.
=> Fix Document.add_all_annotations_from_other()

src/pytorch_ie/core/__init__.py, src/pytorch_ie/core/statistic.py, src/pytorch_ie/metrics/statistics.py, tests/core/test_statistic.py
This add `DocumentStatistics`, an abstract class derived from `DocumentMetrics` to easily collect statistics over datasets. It requires to implement a method `_collect(doc: Document) -> Any`. It should calculate any values over the document, can return naive types (such as int, float, str), dicts, or lists. 
The `_compute()` will aggregate the results of `_collect()` in the following way : naive types are arranged in a list, lists are concatenated, and dictionaries are flattened and their values are handled such as naive types or lists, respectively, and finally unflattened again (this is because calling the `DocumentMetric` on a `DatasetDict` will produce a dictionary with the split names as keys and the metric results as values, so this would result in a semi-flattened dict, if we would …
=> implement DocumentStatistics

src/pytorch_ie/core/metric.py, src/pytorch_ie/core/statistic.py, src/pytorch_ie/metrics/statistics.py, tests/core/test_statistic.py
This PR modifies the `DocumentStatistic` 
- to return aggregated results instead of the lists of collected values. The default aggregation functions can be set via the class variable `DEFAULT_AGGREGATION_FUNCTIONS: List[str]` (the fucntion names are resolved against some inhouse methods (`mean`, `median`, `std`), or python builtin functions and, if this does not work, against the global namespace via `utils.hydra.resolve_target`).
- adds the parameter `show_histogram`: Iff `True` (default: `False`), show the histogram of the collected values with `plotext` on the console
- adds the parameter `show_as_markdown`: Iff `True` (default: `False`), show the result as markdown on the console (requires the `tabulate` package)
- adds the parameter `title`: this is used in the histogram and markdown …
=> aggregate the result of DocumentStatistic

src/pytorch_ie/core/document.py, src/pytorch_ie/data/__init__.py, src/pytorch_ie/data/document_conversion.py, tests/data/test_document_conversion.py, tests/test_document.py
This PR:
- implements `text_based_document_to_token_based()`: convert a text based document + list of tokens + (char_to_token mapper or token_offset_mapping) to a token based document with the respective annotations
- implements `tokenize_document()`: Takes a text based document and a Huggingface tokenizer, produces a list of token based documents with the respective annotations
- modify `Document.add_all_annotations_from_other()`: 
- rename the parameter `override_annotation_mapping` to `override_annotations`
- add parameter `removed_annotations` to allow for annotation removal that is propagated along the annotation graph in the same way as with `override_annotations`
- add parameter `strict` to control if missing annotations will cause an error or are ignored
- add parameter `verbose` …
=> conversion of text based document to token based and tokenize document

src/pytorch_ie/core/statistic.py
When a document statistic returned an empty result list, e.g. when collecting label names for a small dataset split, this was broken because we e.g. divide by the number of entries to  calculate the mean etc. Now, we return `None` in cases where the input list is empty.
=> fix statistic value aggregation for empty result lists

src/pytorch_ie/data/document_conversion.py
useful e.g. for question answering where we want to encode the question in the first sequence (`text` parameter) and the  main text aka context in the second sequence (`text_pair` parameter) 
Note: This also adds the tokenizer encoding as `tokenizer_encoding` to the metadata of the respective document.
=> tokenize_document: set text_pair if text is already provided

src/pytorch_ie/metrics/f1.py
… so that (e.g. document specific) derived classes can easily overwrite it
=> integrate eval_counts_for_layer() into F1Metric.calculate_counts() 

poetry.lock, pyproject.toml, src/pytorch_ie/models/transformer_seq2seq.py
This updates the following dev-dependencies: `sh`, `nox`, and `nox-poetry` (in `pyproject.toml`). It also pins `fsspec` because the latest version causes trouble with `load_dataset`. Then, we called `poetry update` to update the `poetry.lock` file.
=> update (dev) dependencies

poetry.lock, pyproject.toml
We require at least `datasets>=2.13` because of https://github.com/huggingface/datasets/pull/5852 (we rely on the interface changes of `IterableDataset`). This also updates `poetry.lock`.
=> set minimum `datasets` version

src/pytorch_ie/models/interface.py, src/pytorch_ie/models/transformer_seq2seq.py, src/pytorch_ie/models/transformer_span_classification.py, src/pytorch_ie/models/transformer_text_classification.py, src/pytorch_ie/models/transformer_token_classification.py, src/pytorch_ie/taskmodules/interface.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py
These classes don't do anything on its own, but can be used to signal some needs / functionality in downstream projects / scripts.
Model interface classes and usage:
- `RequiresModelNameOrPath` (all models): `TransformerSeq2SeqModel`, `TransformerSpanClassificationModel`, `TransformerTextClassificationModel`, `TransformerTokenClassificationModel`
- `RequiresNumClasses`: `TransformerSpanClassificationModel`, `TransformerTextClassificationModel`, `TransformerTokenClassificationModel`
Taskmodule interface classes and usage:
- `ChangesTokenizerVocabSize`: `TransformerRETextClassificationTaskModule`
=> add model and taskmodule Interface classes

.github/workflows/constraints.txt
TODO:
NOTE: This should be added in a patch release that just contains this PR to test out the release process without breaking further release content.
=> upgrade github workflow constraints

src/pytorch_ie/data/document_conversion.py, tests/data/test_document_conversion.py
in analogy to `text_based_document_to_token_based()` (see #315).
This also adds the following improvements to `text_based_document_to_token_based()`:
- use `tokens`, `token_offset_mapping`, and `char_to_token` from metadata, if available there and not explicitly provided,  and warn, if provided, but different to entries in metadata
- raise an exception if the layers that target the text (the layers we want to modify) consist of annotations that are no `Span`s
=> implement `token_based_document_to_text_based()`

src/pytorch_ie/data/__init__.py, src/pytorch_ie/data/document_conversion.py, tests/data/test_document_conversion.py
this was left out from #334:
- fix the export
- allow string values for `result_document_type` (also for `text_based_document_to_token_based()`)
- improve error message
=> fix and improve `token_based_document_to_text_based()`

src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/data/builder.py, src/pytorch_ie/data/dataset.py, src/pytorch_ie/data/dataset_dict.py, src/pytorch_ie/documents.py, src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py, tests/data/test_builder.py, tests/data/test_dataset.py, tests/data/test_dataset_dict.py
This PR moves the main logic for document preparation, i.e. converting the documents of a loaded dataset to a format that is understood by a taskmodule, to the dataset builder scripts. As a result, that
1) logic is easily sharable via the Huggingface hub, and 
2) allows for document auto-conversion.
With this PR, document converters can be added to dataset builders either as class variable `DOCUMENT_CONVERTS` or dynamically via the parameter `document_converts` when calling `load_dataset()` . In addition, `Dataset`, `IterabelDataset`, and `DatasetDict` have to new methods:
- `register_document_converter(converter, document_type=None)`: register a new convert function for a target document type. If the document type is not provided, it is tried to infer it from the converter return type
- …
=> add document converters

src/pytorch_ie/data/dataset.py, tests/data/test_dataset.py
With this PR, we re-use the original document type when calling `(Iterable)Dataset.map()` if no `result_document_type` is provided. This clarifies the semantics because we do not change the document type except that it is explicitly provided. With this we also do not rely on (maybe wrong) return type annotations anymore and we can use generic functions in map that do not change the document type at all (e.g. trimming spans) which is a quite common case. 
This is a breaking change for the case that `map()` is called with a function that has an annotated return type which is different than the original document type of the dataset.
=> do not try to infer the `document_type` from the function in `(Iterable)Dataset.map()`

tests/__init__.py, tests/data/test_dataset.py
affected tests: `test_load_with_hf_datasets()` and `test_load_with_hf_datasets_from_hub()`
=> skip tests that depend on the HF conll2003 dataset if that is not reachable

src/pytorch_ie/core/__init__.py, src/pytorch_ie/core/metric.py, src/pytorch_ie/core/module_mixins.py, src/pytorch_ie/core/statistic.py, src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/data/dataset.py, src/pytorch_ie/metrics/statistics.py, tests/data/test_dataset.py
Similar to `TaskModules`, `DocumentMetric`s require documents of a certain type as input. This PR adds the functionality to let `DocumentMetrics`s signal what document type they need.
In detail:
- create `RequiresDocumentTypeMixin` that defines the class variable `DOCUMENT_TYPE` and the property `document_type` (which returns `DOCUMENT_TYPE` per default). It also defines the method `convert_dataset()` that checks for several edge cases before calling `dataset.to_document_type(self.document_type)` 
- use `RequiresDocumentTypeMixin` for `DocumentMetric` and also for `TaskModule`
- add the parameter `document_type` to  `DocumentStatistic`s that will be returned when calling `DocumentStatistic.document_type` (it overwrites `DOCUMENT_TYPE`)
- adjust the logic of …
=> `document_type` for `DocumentMetric`s

src/pytorch_ie/data/dataset_dict.py, src/pytorch_ie/utils/hydra.py, tests/data/test_dataset_dict.py, tests/utils/test_hydra.py
With this PR, we serialize the `document_type` when calling `DatasetDict.to_json()`. The `document_type` is saved in a file `metadata.json` in the output path. And it is tried to load it from there when calling `DatasetDict.from_json()` if no `document_type` is specified (which is now optional for this method).
=> (de-)serialize `document_type` when calling `DatasetDict`

src/pytorch_ie/data/dataset_dict.py
With this PR, it is possible to call `DatasetDict.load_dataset(..., split=SPLIT)` or `DatasetDict.from_json(..., split=SPLIT)` to just load the data of a selected `SPLIT`. This is helpful when using large datasets where getting the data and calling `_generate_document()` already takes a lot of time and should not be executed for splits that are not used at all. 
Usage:
- re-install pytorch-ie: `pip uninstall pytorch-ie -y && pip install git+https://github.com/ChristophAlt/pytorch-ie.git@load_dataset_with_split`
- call the eval command with `+dataset.input.split=test` 
Changes:
- `DatasetDict.load_dataset()` and `DatasetDict.from_json()`: unwrap `split` parameter and use it if base `load_dataset()` returns a simple (Huggingface) `(Iterable)Dataset` instead of a `...Dict`
- add type checks …
=> handle `split` parameter for `DatasetDict.load_dataset()`

src/pytorch_ie/documents.py
`TextDocumentWith(Labeled)EntitiesRelationsAndLabeledPartitions` need  to be derived from `TextDocumentWith(Labeled)EntitiesAndLabeledPartitions`, otherwise auto-conversion would fail if we request the latter, but have a converter to the former.
=> Fix document types with partitions

src/pytorch_ie/metrics/statistics.py
With this PR, we allow `labels = "INFERRED"` in which case the labels are inferred from the data. This also adds the parameter `label_attribute`.
**IMPORTANT NOTE: Inferring labels produces wrong results for certain `aggregation_functions` such as `min`, `mean`, and `std` because documents with zero entries of a certain label are not considered anymore for that label. We remove these from `aggregation_functions` if `labels == "INFERRED"`, but we can not handle any user defined function (which relies on correct zero values).**
=> infer labels in `LabelCountCollector`

src/pytorch_ie/metrics/statistics.py, tests/core/test_statistic.py
This PR upgrades `LabeledSpanLengthCollector` to `SpanLengthCollector`: 
- make labels optional and inferrable, 
- add tokenization capability
**IMPORTANT NOTE (similar to #351): Inferring labels produces wrong results for certain `aggregation_functions` such as `min`, `mean`, and `std` because documents with zero entries of a certain label are not considered anymore for that label. We remove these from `aggregation_functions` if `labels == "INFERRED"`, but we can not handle any user defined function (which relies on correct zero values).**
=> upgrade `LabeledSpanLengthCollector` to `SpanLengthCollector`

src/pytorch_ie/metrics/statistics.py, tests/core/test_statistic.py
because, in general, we want to also know the total amounts over the whole dataset. 
This also adds a test for `labels="INFERRED"`
=> add `sum` to default aggregation functions for `LabelCountCollector`

src/pytorch_ie/data/document_conversion.py, tests/data/test_document_conversion.py
... to fix deserialization. Serializing and deserializing `token_offset_mapping` produces lists of lists in any way (json does not know tuples), so we save the entries (start and end offset) as lists in the first place. Otherwise, this breaks equality checks with deserialized documents.
=> save entries of `token_offset_mapping` as lists in document metadata

README.md, examples/predict/re_generative.py, examples/train/span_classification.py, src/pytorch_ie/documents.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py, tests/data/test_builder.py, tests/data/test_dataset.py, tests/models/test_transformer_span_classification.py, tests/pipeline/test_re_generative.py, tests/taskmodules/test_transformer_re_text_classification.py, tests/taskmodules/test_transformer_seq2seq.py, tests/taskmodules/test_transformer_span_classification.py, tests/taskmodules/test_transformer_token_classification.py, tests/test_pipeline.py, tests/train/test_training.py
With this PR, we modify the *generic* document types: rename the annotation layers to reflect the annotation type and also reflect that in the document type names.
**IMPORTANT**: This also changes the default values for annotation layer related parameters in the taskmodules to work with the changes out of the box, i.e.
- `TransformerRETextClassificationTaskModule`: `relation_annotation` becomes `binary_relations` (formerly `relations`) 
- `TransformerSeq2SeqTaskModule`: 
- `entity_annotation` becomes `labeled_spans` (formerly `entities`), and
- `relation_annotation` becomes `binary_relations` (formerly `relations`)
- `TransformerSpanClassificationTaskModule`: `entity_annotation` becomes `labeled_spans` (formerly `entities`)
- `TransformerTokenClassificationTaskModule`: `entity_annotation` …
=> adjust generic document types

src/pytorch_ie/data/dataset.py, tests/data/test_dataset.py
i.e. no silent auto-cast anymore to increase transparency and to mitigate bugs
=> auto-conversion requires a matching entry in `document_converts`

src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py
With this PR, we check if the annotation layer names required in the taskmodules match the ones in the document types that they usually would request and request no document type in the case of a mismatch (bot log a warning).
This also changes the default value for `annotation` in `TransformerTextClassificationTaskModule` to `"label"` to match the requested document type.
=> Fix `document_type` property of taskmodules

src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/data/dataset.py, src/pytorch_ie/pipeline.py, tests/data/test_dataset.py, tests/test_pipeline.py
This is in preparation for outsourcing the complete logic related to PyTorch-IE  `Dataset`, `IterableDataset`, and `DatasetDict` to [pie-datasets](https://github.com/ArneBinder/pie-datasets) (see https://github.com/ArneBinder/pie-datasets/pull/21).
=> decouple `(Iterable)Dataset` from core framework (except for tests)

src/pytorch_ie/metrics/statistics.py, tests/conftest.py, tests/metrics/test_statistics.py
This reverts some of the changes of #366, i.e. it re-adds the following statistics (and simplifies their tests):
- `TokenCountCollector`: Collects the token count of a field when tokenizing its content with a Huggingface tokenizer.
- `FieldLengthCollector`: Collects the length of a field, e.g. to collect the number the characters in the input text.
- `SubFieldLengthCollector`: Collects the length of a subfield in a field, e.g. to collect the number of arguments of N-ary relations.
- `DummyCollector`: A dummy collector that always returns 1, e.g. to count the number of documents. 
Note, that the `SpanLengthCollector` stays in [pie-datasets](https://github.com/ArneBinder/pie-datasets), because it uses `pie_datasets.document.conversion.tokenize_document`.
=> re-add some statistics

README.md, examples/predict/ner_span_classification.py, examples/predict/re_generative.py, examples/predict/re_text_classification.py, src/pytorch_ie/core/__init__.py, src/pytorch_ie/core/document.py, src/pytorch_ie/core/metric.py, src/pytorch_ie/core/module_mixins.py, src/pytorch_ie/core/taskmodule.py, src/pytorch_ie/documents.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, tests/conftest.py, tests/core/test_document.py, tests/core/test_metric.py, tests/metrics/test_f1.py, tests/pipeline/test_ner_span_classification.py, tests/pipeline/test_re_generative.py, tests/pipeline/test_re_text_classification.py, tests/taskmodules/test_simple_transformer_text_classification.py, tests/taskmodules/test_transformer_seq2seq.py, tests/taskmodules/test_transformer_token_classification.py, tests/test_auto.py, tests/test_document.py
This PR renames:
- `AnnotationList` to `AnnotationLayer`, and
- `RequiresDocumentTypeMixin` to `WithDocumentTypeMixin`.
Note: The classes are still available via the old names as aliases.
=> rename core classes

src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/module_mixins.py, src/pytorch_ie/core/taskmodule.py
This PR outsources code related to module preparation from the `TaskModule` into a `PreparableMixin` class. It also fixes minor preparation logic issues and ensures that a taskmodule is prepared when calling `encode()`.
=> implement `PreparableMixin`

src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_seq2seq.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py
This removes leftovers of #371.
=> remove `is_training` parameter from taskmodule implementations

src/pytorch_ie/__init__.py, src/pytorch_ie/taskmodules/__init__.py, tests/models/test_transformer_seq2seq.py, tests/models/test_transformer_span_classification.py, tests/taskmodules/test_simple_transformer_text_classification.py, tests/taskmodules/test_transformer_re_text_classification.py, tests/taskmodules/test_transformer_seq2seq.py, tests/taskmodules/test_transformer_span_classification.py, tests/taskmodules/test_transformer_token_classification.py
Changes:
- export everything from `core`
- do not directly export anything from `models` and `taskmodules` anymore (to align with all other "implementations", i.e. `documents`, `annotations`, and `metrics`)
TODO:
=> re-arrange exports

src/pytorch_ie/documents.py
When used in a dataset, the document gets serialized to json like structure which does not know tuples, so they get converted to lists. This is a workaround to automatically convert the `tokens` field back to tuples when the document is created from a dataset.
=> fix `TokenBasedDocument`: convert tokens to tuple if they are a list

src/pytorch_ie/core/taskmodule.py
This adds the interface method `configure_model_metric(stage: str) -> Optional[Metric]` to the `TaskModule` class. Per default, it returns just `None`. Taskmodule implementations can override this to return a `torchmetrics.Metric` which should accept a batch of model outputs and targets. By having this method defined in the taskmodule, it is possible to use its `unbatch_output` and any available annotation decoding logic. Then, a `PyTorchIEModel` implementation can use this to easily create metrics that match the data without re-implementing any specific decoding logic.
=> add `TaskModule.configure_model_metric(stage)`

src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/taskmodule.py, tests/test_auto.py
The loaded task module should be ready to use when loading from config, in the same way as when loading from pretrained. This was missed in #395.
=> call `post_prepare()` in `TaskModuel._from_config()`

src/pytorch_ie/annotations.py, src/pytorch_ie/core/document.py, tests/test_document.py
With this PR, the properties `Annotation.(target|targets|named_targets)` return never None, **but raise a `ValueError` if the annotation is not attached** to a document. This clarifies the semantics and mitigates typing issues. It is recommended to first check with `Annotation.is_attached` before using one of the above properties.
Note: This also changes the string representation of the `Span` annotation if it is not attached to just returning `super().__str__()` (instead of the empty string as it was before).
=> `Annotation.(target|targets|named_targets)` return never `None`

src/pytorch_ie/annotations.py, tests/test_annotations.py
The `LabeledMultiSpan` was moved to `pie-modules` (and also fixed), see https://github.com/ArneBinder/pie-modules/pull/59. So we remove it from `pytorch-ie` to mitigate any confusion caused by two implementations (note that comparison would break when comparing an instance of one with the other even if the implemented semantics are identical).
Note that this also removes `_post_init_multi_span()`.
=> Remove `(Multi)LabeledMultiSpan` annotations

src/pytorch_ie/core/document.py, tests/core/test_document.py
This PR adds the following class methods to `Document`:
- `target_names(field_name: str) -> Set[str]`: Return the target names of an annotation field.
- `target_name(field_name: str) -> str`: Return the single target name of an annotation field. Raises an error if the field has less or more than one target.
=> add `target_name(str)` and `target_names(str)` to `Document`

src/pytorch_ie/annotations.py, src/pytorch_ie/core/document.py, tests/core/test_document.py, tests/test_annotations.py
This adds the `Annotation.resolve()` interface. It is meant to get a well readable representation (similar to the string representation), but still as a structured object for easy comparison e.g. in tests. This also adds implementations to all annotation classes.
Note: This also adds all missing tests for `NaryRelation` (there were no tests at all for this annotation type).
=> implement `Annotation.resolve()`

src/pytorch_ie/annotations.py, src/pytorch_ie/documents.py, tests/test_annotations.py
This PR adds the annotation types: 
- `MultiSpan` and 
- `LabeledMultiSpan`.
It also adds the following document types:
- `TextDocumentWithLabeledMultiSpans`, 
- `TextDocumentWithLabeledMultiSpansAndLabeledPartitions`,
- `TextDocumentWithLabeledMultiSpansAndBinaryRelations`, and
- `TextDocumentWithLabeledMultiSpansBinaryRelationsAndLabeledPartitions`.
=> Add multi span annotation types and documents

src/pytorch_ie/core/document.py, tests/test_document.py
… from original annotations that were added to new ones instead of a just a list consisting of the former.
Note: This is breaking because it changes the interface of  `Document.add_all_annotations_from_other`.
=> `Document.add_all_annotations_from_other` returns a mapping

README.md
Since we published the [Pytorch-IE paper on arXiv](https://arxiv.org/abs/2406.00007), we can mention it in the readme. Closes #422.
=> update paper ref

src/pytorch_ie/metrics/f1.py, tests/metrics/test_f1.py
Until now, we just used the gold data for that. This impacts the MACRO value, because in the case where entries with a certain label are only in the predictions we will now get a zero score for that label which decreases the macro average, but before this was left out. However, this should have only an effect on very small data where there are really more labels in prediction than in gold.
=> `F1Metric`: infer labels also from predicted annotations

.github/workflows/labeler.yml, .github/workflows/release.yml, .github/workflows/tests.yml, src/pytorch_ie/pipeline.py
see https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Note: This also bumps all remaining actions to latest version (except codecov-action because of added token requirement).
=> fix tests (outdated upload/download-artifact)

src/pytorch_ie/core/document.py, tests/test_document.py
With this PR, `Document.add_all_annotations_from_other()` returns a dict with annotation **ids** instead of annotations as keys. The state before, returning a dict with annotations as keys, was problematic because, there may be multiple annotations with the same hash (e.g. when only non-comparison files such as the `score` are different) which results in dropped / overwritten entries.
=> fix `Document.add_all_annotations_from_other()`

src/pytorch_ie/core/document.py, src/pytorch_ie/utils/document.py, tests/utils/test_document.py
This PR implements `utils.document.merge_annotations_from_documents()`. From the doscstring:
```
"""Merge annotations from multiple documents into a single document. Optionally, store the source
names for all annotations / predictions in the metadata at key metadata_key_source_annotations
/ metadata_key_source_predictions, respectively.
Note that this will remove any annotation duplicates.
Args:
documents: A dictionary mapping document source (e.g. dataset names) to documents.
metadata_key_source_annotations: If not None, the key in the metadata where the source names
for the (gold) annotations are stored.
metadata_key_source_predictions: If not None, the key in the metadata where the source names
for the predictions are stored.
Returns:
The document with merged annotations.
"""
``` …
=> implement `merge_annotations_from_documents()`

src/pytorch_ie/auto.py, src/pytorch_ie/core/hf_hub_mixin.py
to make it overwritable. This also:
- fixes some typing
- parametrizes `weights_file_name`
- for consistence, also adds `save_model_file`
=> outsource `PieModelHFHubMixin.load_model_file`

src/pytorch_ie/utils/document.py, tests/utils/test_document.py
Note: this changes (fixes?) the semantics of `utils.document.merge_annotations_from_documents`!
=> remove `utils.document.deduplicate_annotations` in favor of `Document.deduplicate_annotations`

src/pytorch_ie/pipeline.py
This also removes:
- the parameter `binary_output` because it was not used, and
- the parameter `shuffle` because, if set, it would collide with hardcoded `shuffle=False` in the dataloader setup.
=> `Pipeline`: cleanup and improve docs

src/pytorch_ie/pipeline.py, src/pytorch_ie/taskmodules/simple_transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_re_text_classification.py, src/pytorch_ie/taskmodules/transformer_span_classification.py, src/pytorch_ie/taskmodules/transformer_text_classification.py, src/pytorch_ie/taskmodules/transformer_token_classification.py, tests/pipeline/test_re_text_classification.py
This PR implements half and mixed precision inference by adding the following boolean parameters to the `Pipeline`:
- `half_precision_model`:  Whether or not to use half precision model. If set to `True`, the model will be cast to half precision on supported devices (`torch.float16` on `cuda` and `torch.bfloat16` on `cpu` for now, following `torch.get_autocast_dtype()`). This can reduce the memory consumption and improve the inference speed, but may lead to numerical instability.
- `half_precision_ops`: Whether or not to use half precision operations. If set to `True`, the model will be run with half precision operations via [torch.autocast](https://pytorch.org/docs/stable/amp.html#torch.autocast).
Since `torch.float16` can not be natively converted to `numpy`, this PR adds `float()` …
=> half and mixed precision inference

.github/workflows/release.yml, .github/workflows/tests.yml
especially for `actions/cache` to fix the version issue, see https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down for context
Same as https://github.com/ArneBinder/pie-datasets/pull/170.
=> CI: define only major version for all actions from Github

src/pytorch_ie/metrics/__init__.py, src/pytorch_ie/metrics/confusion_matrix.py, tests/metrics/test_confusion_matrix.py
This PR implements the document metric `ConfusionMatrix`. From the docstring:
```
Computes the confusion matrix for a given annotation layer that contains labeled annotations.
Args:
layer: The layer to compute the confusion matrix for.
label_field: The field to use for the label. Defaults to "label".
unassignable_label: The label to use for false negative annotations. Defaults to "UNASSIGNABLE".
undetected_label: The label to use for false positive annotations. Defaults to "UNDETECTED".
strict: If True, raises an error if a base annotation has multiple gold labels. If False, logs a warning.
show_as_markdown: If True, logs the confusion matrix as markdown on the console when calling compute().
annotation_processor: A callable that processes the annotations before calculating the confusion …
```
=> implement `ConfusionMatrix` document metric

src/pytorch_ie/auto.py, src/pytorch_ie/core/hf_hub_mixin.py, src/pytorch_ie/core/taskmodule.py
With this PR, it is now possible to overwrite individual config entries that are arbitrarily nested. Does work for dicts, but not for lists.
This also adds the parameter `config_override` to `_from_pretrained` and `_from_config` to provide fine-grained control over this behavior. It accepts a `bool` value or a `dict` mapping from config keys to `bool` or `dict` values again, this can be recursive. If `True`, the value for the respective key (or the whole config, on the top level) is taken from the keyword arguments. If `False`, the keyword argument is discarded and the respective config value is taken. If it is `None` or if no `bool` value is set for the respective key, the keyword arguments are merged recursively into the config .
TODO:
=> nested config update in `_from_pretrained` and `_from_config`

.github/workflows/release.yml
since the release workflow seems to be broken after #480
=> enable verbose for publish to test PyPi

poetry.lock, pyproject.toml
see https://github.com/ArneBinder/pie-core/releases/tag/v0.3.0
This is **breaking'** because pie-core 0.3.0 was a breaking release and some of these elements re-exported:
- `WithDocumentTypeMixin` (alias: `RequiresDocumentTypeMixin`)
- (`AnnotationPipeline`|`Model`|`TaskModule`).(`from_pretrained`|`save_pretrained`)
=> allow `pie-core 0.3.0` and update lock file to that version

poetry.lock, pyproject.toml
since it is soon covered in pie-datasets, see https://github.com/ArneBinder/pie-datasets/pull/198
**breaking** since it does not enforce dependency constraints anymore
=> remove `fsspec` constraint from dependencies

tests/test_pipeline.py
make a copy to ensure original documents are not modified in non-inplace mode. 
background: This is a regression introduced in #498, where we changed the scope of the `documents` fixture to `module`.
=> fix `test_pipeline_with_documents`

tests/test_pipeline.py
#505 did not work out as expected, so we need to try again.
Note that this test fails **only on the main branch CI**, since it is (was) marked as `slow`. unfortunately, I can not reproduce locally.
TODO:
=> fix failing test `test_pipeline_with_documents`
